<?php
return array (
  40 => 
  array (
    'posid' => '40',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页热门300x250',
    'maxnum' => '200',
    'extention' => '',
    'listorder' => '100',
    'siteid' => '0',
    'thumb' => '',
  ),
  26 => 
  array (
    'posid' => '26',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页幻灯片350x350',
    'maxnum' => '200',
    'extention' => '',
    'listorder' => '100',
    'siteid' => '0',
    'thumb' => '',
  ),
  25 => 
  array (
    'posid' => '25',
    'modelid' => '0',
    'catid' => '0',
    'name' => '推荐',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '99',
    'siteid' => '0',
    'thumb' => '',
  ),
  32 => 
  array (
    'posid' => '32',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页推荐4',
    'maxnum' => '200',
    'extention' => '',
    'listorder' => '98',
    'siteid' => '0',
    'thumb' => '',
  ),
  31 => 
  array (
    'posid' => '31',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页推荐3',
    'maxnum' => '200',
    'extention' => '',
    'listorder' => '98',
    'siteid' => '0',
    'thumb' => '',
  ),
  28 => 
  array (
    'posid' => '28',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页推介2',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '98',
    'siteid' => '1',
    'thumb' => '',
  ),
  27 => 
  array (
    'posid' => '27',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页推介1',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '98',
    'siteid' => '1',
    'thumb' => '',
  ),
  36 => 
  array (
    'posid' => '36',
    'modelid' => '1',
    'catid' => '0',
    'name' => '名人推荐',
    'maxnum' => '8000',
    'extention' => '',
    'listorder' => '10',
    'siteid' => '0',
    'thumb' => '',
  ),
  35 => 
  array (
    'posid' => '35',
    'modelid' => '2',
    'catid' => '0',
    'name' => '朝代文章推介',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '10',
    'siteid' => '1',
    'thumb' => '',
  ),
  34 => 
  array (
    'posid' => '34',
    'modelid' => '0',
    'catid' => '0',
    'name' => '头条推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '9',
    'siteid' => '0',
    'thumb' => '',
  ),
  29 => 
  array (
    'posid' => '29',
    'modelid' => '0',
    'catid' => '0',
    'name' => '话题图文推介',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '2',
    'siteid' => '1',
    'thumb' => '',
  ),
  33 => 
  array (
    'posid' => '33',
    'modelid' => '3',
    'catid' => '38',
    'name' => '话题推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '1',
    'siteid' => '1',
    'thumb' => '',
  ),
  39 => 
  array (
    'posid' => '39',
    'modelid' => '1',
    'catid' => '0',
    'name' => '热门话题人物推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  43 => 
  array (
    'posid' => '43',
    'modelid' => '15',
    'catid' => '0',
    'name' => '老照片首页推荐',
    'maxnum' => '200',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '3',
    'thumb' => '',
  ),
  42 => 
  array (
    'posid' => '42',
    'modelid' => '15',
    'catid' => '0',
    'name' => '老照片幻灯推荐',
    'maxnum' => '200',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '3',
    'thumb' => '',
  ),
  41 => 
  array (
    'posid' => '41',
    'modelid' => '0',
    'catid' => '0',
    'name' => '手机端首页幻灯',
    'maxnum' => '200',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  45 => 
  array (
    'posid' => '45',
    'modelid' => '15',
    'catid' => '0',
    'name' => '美女图推荐',
    'maxnum' => '2000',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '3',
    'thumb' => '',
  ),
  38 => 
  array (
    'posid' => '38',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页老照片推荐',
    'maxnum' => '100',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  18 => 
  array (
    'posid' => '18',
    'modelid' => '1',
    'catid' => '1',
    'name' => '皇帝',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  24 => 
  array (
    'posid' => '24',
    'modelid' => '1',
    'catid' => '1',
    'name' => '其他',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  23 => 
  array (
    'posid' => '23',
    'modelid' => '1',
    'catid' => '1',
    'name' => '虚构',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  22 => 
  array (
    'posid' => '22',
    'modelid' => '1',
    'catid' => '1',
    'name' => '美女',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  21 => 
  array (
    'posid' => '21',
    'modelid' => '1',
    'catid' => '1',
    'name' => '文臣',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  20 => 
  array (
    'posid' => '20',
    'modelid' => '1',
    'catid' => '1',
    'name' => '武将',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  19 => 
  array (
    'posid' => '19',
    'modelid' => '1',
    'catid' => '1',
    'name' => '皇后',
    'maxnum' => '32767',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  46 => 
  array (
    'posid' => '46',
    'modelid' => '0',
    'catid' => '0',
    'name' => '优化推荐',
    'maxnum' => '2000',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
);
?>