<?php
return array (
  1 => 
  array (
    'siteid' => '1',
    'name' => '讲历史',
    'dirname' => '',
    'domain' => 'http://www.jianglishi.cn/',
    'site_title' => '中国历史，历史故事，中国历史朝代表 - 讲历史',
    'keywords' => '中国历史，中国历史朝代表，历史上的今天，历史故事',
    'description' => '讲历史是国内最好的历史网站，一个历史知识的百科大全。讲历史专注于搜集整理中国各朝代人物、战争、野史、文化等全方面历史知识，以及环球各个国家历史文化，为您提供全面的历史知识阅读学习平台，推荐看历史就来讲历史。',
    'release_point' => '',
    'default_style' => 'jianglishi',
    'template' => 'jianglishi',
    'setting' => 'array (
  \'upload_maxsize\' => \'2048\',
  \'upload_allowext\' => \'jpg|jpeg|gif|bmp|png|doc|docx|xls|xlsx|ppt|pptx|pdf|txt|rar|zip|swf\',
  \'watermark_enable\' => \'1\',
  \'watermark_minwidth\' => \'240\',
  \'watermark_minheight\' => \'200\',
  \'watermark_img\' => \'statics/images/water//mark.png\',
  \'watermark_pct\' => \'100\',
  \'watermark_quality\' => \'40\',
  \'watermark_pos\' => \'9\',
)',
    'uuid' => '42e16e45-073e-1034-9802-6363c6b74531',
    'url' => 'http://www.jianglishi.cn/',
  ),
  3 => 
  array (
    'siteid' => '3',
    'name' => '老照片',
    'dirname' => 'laozhaopian',
    'domain' => 'http://www.jianglishi.cn/laozhaopian/',
    'site_title' => '老照片_历史照片_历史图片 - 讲历史',
    'keywords' => '老照片,历史照片,历史图片,历史图集',
    'description' => '老照片，顾名思义是老旧的照片，老时代的照片。老照片汇集了中国历史照片、图集，中国名人照片，战争照片，古玩照片等等。',
    'release_point' => '',
    'default_style' => 'laozhaopian',
    'template' => 'laozhaopian',
    'setting' => 'array (
  \'upload_maxsize\' => \'2000\',
  \'upload_allowext\' => \'jpg|jpeg|gif|bmp|png|doc|docx|xls|xlsx|ppt|pptx|pdf|txt|rar|zip|swf\',
  \'watermark_enable\' => \'0\',
  \'watermark_minwidth\' => \'300\',
  \'watermark_minheight\' => \'300\',
  \'watermark_img\' => \'statics/images/water//mark.gif\',
  \'watermark_pct\' => \'100\',
  \'watermark_quality\' => \'40\',
  \'watermark_pos\' => \'9\',
)',
    'uuid' => '',
    'url' => 'http://www.jianglishi.cn/laozhaopian/',
  ),
);
?>