<?php
return array (
  1 => 
  array (
    'typeid' => '1',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '上古',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => 'shanggu',
  ),
  2 => 
  array (
    'typeid' => '2',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '夏朝',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => 'xiachao',
  ),
  3 => 
  array (
    'typeid' => '3',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '商朝',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => 'shangchao',
  ),
  4 => 
  array (
    'typeid' => '4',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '周朝',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => 'zhouchao',
  ),
  5 => 
  array (
    'typeid' => '5',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '春秋战国',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => 'chunqiu',
  ),
  6 => 
  array (
    'typeid' => '6',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '秦朝',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => 'qinchao',
  ),
  7 => 
  array (
    'typeid' => '7',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '汉朝',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => 'hanchao',
  ),
  8 => 
  array (
    'typeid' => '8',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '三国',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => 'sanguo',
  ),
  9 => 
  array (
    'typeid' => '9',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '晋朝',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => 'jinchao',
  ),
  10 => 
  array (
    'typeid' => '10',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '南北朝',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => 'nanbeichao',
  ),
  11 => 
  array (
    'typeid' => '11',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '隋朝',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => 'suichao',
  ),
  12 => 
  array (
    'typeid' => '12',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '唐朝',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => 'tangchao',
  ),
  13 => 
  array (
    'typeid' => '13',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '五代十国',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => 'wudai',
  ),
  14 => 
  array (
    'typeid' => '14',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '宋朝',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => 'songchao',
  ),
  15 => 
  array (
    'typeid' => '15',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '元朝',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => 'yuanchao',
  ),
  16 => 
  array (
    'typeid' => '16',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '明朝',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => 'mingchao',
  ),
  17 => 
  array (
    'typeid' => '17',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '清朝',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => 'qingchao',
  ),
  18 => 
  array (
    'typeid' => '18',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '民国',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => 'minguo',
  ),
  19 => 
  array (
    'typeid' => '19',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '近代',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => 'jindai',
  ),
);
?>