<?php
return array (
  5 => 
  array (
    'workflowid' => '5',
    'siteid' => '3',
    'steps' => '2',
    'workname' => '二级审核',
    'description' => '',
    'setting' => 'array (
  1 => 
  array (
    0 => \'gt\',
    1 => \'meng\',
    2 => \'ceshi22\',
  ),
  2 => 
  array (
    0 => \'gt\',
    1 => \'meng\',
  ),
  3 => \'\',
  4 => \'\',
  \'nocheck_users\' => 
  array (
    0 => \'gt\',
  ),
)',
    'flag' => '1',
  ),
  6 => 
  array (
    'workflowid' => '6',
    'siteid' => '3',
    'steps' => '1',
    'workname' => '一级审核',
    'description' => '',
    'setting' => 'array (
  1 => 
  array (
    0 => \'ceshi\',
    1 => \'xieyan\',
    2 => \'meng\',
    3 => \'ceshi22\',
    4 => \'xiaohao\',
    5 => \'edit_010\',
    6 => \'edit_bai\',
    7 => \'edit_jr1\',
    8 => \'edit_ed151\',
    9 => \'edit_thunder\',
    10 => \'edit_jian\',
    11 => \'edit_david\',
    12 => \'edit_shui\',
    13 => \'edit_feng\',
    14 => \'edit_ming\',
    15 => \'edit_fangao\',
    16 => \'edit_yi\',
    17 => \'edit_Elina\',
    18 => \'edit_HU\',
    19 => \'edit_zero\',
    20 => \'edit_lin\',
    21 => \'edit_wei\',
    22 => \'edit_chen\',
    23 => \'edit_xin\',
    24 => \'edit_Beata\',
    25 => \'edit_ada\',
    26 => \'edit_yuzhe\',
    27 => \'edit_mengmeng\',
    28 => \'edit_xy\',
    29 => \'edit_fang\',
    30 => \'edit_lady\',
    31 => \'edit_hulei\',
    32 => \'edit_101\',
    33 => \'edit_yutian\',
    34 => \'edit_duobao\',
    35 => \'edit_bojue\',
    36 => \'edit_Annie\',
    37 => \'edit_lanshui\',
    38 => \'edit_lingdan\',
    39 => \'edit_Bonnie\',
    40 => \'edit_xiaogui\',
    41 => \'edit_yanqun\',
    42 => \'edit_baicai\',
    43 => \'edit_cengfeng\',
    44 => \'edit_yun\',
    45 => \'edit_mengdie\',
    46 => \'edit_shanshui\',
    47 => \'edit_yiluo\',
    48 => \'edit_SEVEN\',
    49 => \'edit_shimin\',
    50 => \'edit_hulu\',
    51 => \'edit_lutu\',
    52 => \'edit_nuoyi\',
    53 => \'edit_lakd\',
    54 => \'edit_Joa\',
    55 => \'edit_102\',
    56 => \'edit_Porlin\',
    57 => \'edit_Any\',
    58 => \'edit_cool\',
    59 => \'edit_Nie\',
    60 => \'edit_ieso\',
    61 => \'edit_milan\',
    62 => \'edit_linyc\',
    63 => \'edit_yu\',
    64 => \'edit_yuwei\',
    65 => \'edit_duoduo\',
    66 => \'edit_hehao\',
    67 => \'edit_yi001\',
    68 => \'Author_king\',
    69 => \'edit_yi002\',
    70 => \'edit_yi003\',
    71 => \'edit_yi004\',
    72 => \'edit_yi005\',
    73 => \'edit_xing\',
    74 => \'edit_yi006\',
    75 => \'edit_yi007\',
    76 => \'edit_yi008\',
    77 => \'edit_yi009\',
    78 => \'edit_yi010\',
    79 => \'edit_yi011\',
    80 => \'edit_youjin\',
    81 => \'Author_art\',
    82 => \'edit_princess\',
    83 => \'edit_damai\',
    84 => \'edit_xiaotuzi\',
    85 => \'edit_xiaoyang\',
    86 => \'edit_PetPet\',
    87 => \'edit_ashui\',
    88 => \'edit_shudashui\',
    89 => \'edit_fanhua\',
    90 => \'edit_yushui\',
    91 => \'edit_Emear\',
    92 => \'edit_huang\',
    93 => \'edit_fengguoer\',
    94 => \'edit_dafengqi\',
    95 => \'edit_yi013\',
    96 => \'Author_chenchen\',
    97 => \'Author_LEFT\',
    98 => \'Author_amy\',
    99 => \'edit_yuytian\',
    100 => \'edit_jxsf\',
    101 => \'edit_lanlan\',
    102 => \'edit_yi012\',
    103 => \'edit_Laughing\',
    104 => \'edit_yi014\',
    105 => \'edit_yi015\',
    106 => \'edit_yi016\',
    107 => \'Author_tang\',
    108 => \'edit_boai\',
    109 => \'edit_ele\',
    110 => \'edit_amuu\',
    111 => \'edit_tong\',
    112 => \'Author_wu\',
    113 => \'edit_shale\',
    114 => \'edit_ruo\',
    115 => \'edit_cicy\',
    116 => \'edit_Kiky\',
    117 => \'edit_cenxin\',
    118 => \'Author_LAPLAND\',
  ),
  2 => \'\',
  3 => \'\',
  4 => \'\',
  \'nocheck_users\' => 
  array (
    0 => \'meng\',
  ),
)',
    'flag' => '0',
  ),
  7 => 
  array (
    'workflowid' => '7',
    'siteid' => '3',
    'steps' => '3',
    'workname' => '三审',
    'description' => '',
    'setting' => 'array (
  1 => 
  array (
    0 => \'gt\',
  ),
  2 => 
  array (
    0 => \'gt\',
  ),
  3 => 
  array (
    0 => \'gt\',
  ),
  4 => \'\',
  \'nocheck_users\' => \'\',
)',
    'flag' => '1',
  ),
);
?>