<?php
return array (
  1 => 
  array (
    'workflowid' => '1',
    'siteid' => '1',
    'steps' => '1',
    'workname' => '一级审核',
    'description' => '审核一次',
    'setting' => 'array (
  1 => 
  array (
    0 => \'xieyan\',
    1 => \'卢广松\',
    2 => \'meng\',
    3 => \'ceshi22\',
    4 => \'ngt\',
    5 => \'xr\',
  ),
  2 => \'\',
  3 => \'\',
  4 => \'\',
  \'nocheck_users\' => 
  array (
    0 => \'meng\',
  ),
)',
    'flag' => '1',
  ),
  2 => 
  array (
    'workflowid' => '2',
    'siteid' => '1',
    'steps' => '2',
    'workname' => '二级审核',
    'description' => '审核两次',
    'setting' => 'array (
  1 => 
  array (
    0 => \'ceshi\',
    1 => \'meng\',
    2 => \'ceshi22\',
    3 => \'edit_010\',
    4 => \'edit_bai\',
    5 => \'edit_jr1\',
    6 => \'edit_ed151\',
    7 => \'edit_thunder\',
    8 => \'edit_jian\',
    9 => \'edit_david\',
    10 => \'edit_shui\',
    11 => \'edit_feng\',
    12 => \'edit_ming\',
    13 => \'edit_fangao\',
    14 => \'edit_yi\',
    15 => \'edit_Elina\',
    16 => \'edit_HU\',
    17 => \'edit_zero\',
    18 => \'edit_lin\',
    19 => \'edit_wei\',
    20 => \'edit_chen\',
    21 => \'edit_xin\',
    22 => \'edit_Beata\',
    23 => \'edit_ada\',
    24 => \'edit_yuzhe\',
    25 => \'edit_mengmeng\',
    26 => \'edit_xy\',
    27 => \'edit_fang\',
    28 => \'edit_lady\',
    29 => \'edit_hulei\',
    30 => \'edit_101\',
    31 => \'edit_yutian\',
    32 => \'edit_duobao\',
    33 => \'edit_bojue\',
    34 => \'edit_Annie\',
    35 => \'edit_lanshui\',
    36 => \'edit_lingdan\',
    37 => \'edit_Bonnie\',
    38 => \'edit_xiaogui\',
    39 => \'edit_yanqun\',
    40 => \'edit_baicai\',
    41 => \'edit_cengfeng\',
    42 => \'edit_yun\',
    43 => \'edit_mengdie\',
    44 => \'edit_shanshui\',
    45 => \'edit_yiluo\',
    46 => \'edit_SEVEN\',
    47 => \'edit_shimin\',
    48 => \'edit_hulu\',
    49 => \'edit_lutu\',
    50 => \'edit_nuoyi\',
    51 => \'edit_lakd\',
    52 => \'edit_Joa\',
    53 => \'edit_102\',
    54 => \'edit_Porlin\',
    55 => \'edit_Any\',
    56 => \'edit_cool\',
    57 => \'edit_Nie\',
    58 => \'edit_ieso\',
    59 => \'edit_milan\',
    60 => \'edit_linyc\',
    61 => \'edit_yu\',
    62 => \'edit_yuwei\',
    63 => \'edit_duoduo\',
    64 => \'edit_hehao\',
    65 => \'edit_yi001\',
    66 => \'Author_king\',
    67 => \'edit_yi002\',
    68 => \'edit_yi003\',
    69 => \'edit_yi004\',
    70 => \'edit_yi005\',
    71 => \'edit_xing\',
    72 => \'edit_yi006\',
    73 => \'edit_yi007\',
    74 => \'edit_yi008\',
    75 => \'edit_yi009\',
    76 => \'edit_yi010\',
    77 => \'edit_yi011\',
    78 => \'edit_youjin\',
    79 => \'Author_art\',
    80 => \'edit_princess\',
    81 => \'edit_damai\',
    82 => \'edit_xiaotuzi\',
    83 => \'edit_xiaoyang\',
    84 => \'edit_PetPet\',
    85 => \'edit_ashui\',
    86 => \'edit_shudashui\',
    87 => \'edit_fanhua\',
    88 => \'edit_yushui\',
    89 => \'edit_Emear\',
    90 => \'edit_huang\',
    91 => \'edit_fengguoer\',
    92 => \'edit_dafengqi\',
    93 => \'edit_yi013\',
    94 => \'Author_chenchen\',
    95 => \'Author_LEFT\',
    96 => \'edit_yuytian\',
    97 => \'edit_jxsf\',
    98 => \'edit_lanlan\',
    99 => \'edit_yi012\',
    100 => \'edit_Laughing\',
    101 => \'edit_yi014\',
    102 => \'edit_yi015\',
    103 => \'edit_yi016\',
    104 => \'Author_tang\',
    105 => \'edit_boai\',
    106 => \'edit_ele\',
    107 => \'edit_amuu\',
    108 => \'edit_tong\',
    109 => \'Author_wu\',
    110 => \'edit_shale\',
    111 => \'edit_ruo\',
    112 => \'edit_cicy\',
    113 => \'edit_Kiky\',
    114 => \'edit_cenxin\',
    115 => \'Author_LAPLAND\',
    116 => \'edit_yi017\',
    117 => \'edit_pushi\',
    118 => \'edit_yi018\',
    119 => \'edit_yi019\',
    120 => \'edit_020\',
    121 => \'edit_yi021\',
    122 => \'edit_yi022\',
    123 => \'edit_yi023\',
    124 => \'edit_yi024\',
    125 => \'Author_025\',
    126 => \'edit_yi025\',
    127 => \'edit_yi026\',
    128 => \'edit_yi027\',
    129 => \'edit_yi028\',
    130 => \'edit_yi032\',
    131 => \'edit_yi029\',
    132 => \'edit_031\',
    133 => \'edit_yi030\',
    134 => \'edit_yi031\',
    135 => \'ngt\',
    136 => \'edit_yi033\',
    137 => \'edit_yi034\',
    138 => \'edit_yi035\',
    139 => \'edit_re\',
    140 => \'xr\',
    141 => \'edit_xu\',
    142 => \'js\',
    143 => \'dj\',
  ),
  2 => 
  array (
    0 => \'ceshi\',
    1 => \'meng\',
    2 => \'ngt\',
    3 => \'xr\',
    4 => \'js\',
    5 => \'dj\',
  ),
  3 => \'\',
  4 => \'\',
  \'nocheck_users\' => \'\',
)',
    'flag' => '1',
  ),
  3 => 
  array (
    'workflowid' => '3',
    'siteid' => '1',
    'steps' => '3',
    'workname' => '三级审核',
    'description' => '审核三次',
    'setting' => '',
    'flag' => '0',
  ),
  4 => 
  array (
    'workflowid' => '4',
    'siteid' => '1',
    'steps' => '4',
    'workname' => '四级审核',
    'description' => '四级审核',
    'setting' => '',
    'flag' => '0',
  ),
);
?>